version: '3'

include:
  - docker-compose.kafka.yaml

services:
  app:
    build: .
    command: .docker/start.dev.sh
    stop_signal: SIGKILL
    stdin_open: true
    tty: true
    privileged: true
    env_file:
      - ./envs/.env
    volumes:
      - .:/home/node/app
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ~/.docker/config.json:/home/node/.docker/config.json:ro
    ports:
      - 3001:3000
    
  elasticsearch:
    image: elasticsearch:7.17.7
    environment:
      - discovery.type=single-node
    ports:
      - 9400:9200

  
      
  
  # memcached:
  #   image: memcached:1.6.23-alpine3.19
  #   ports:
  #     - 11211:11211
