version: '3'

services:
  app:
    build: .
    command: .docker/start.dev.sh
    stop_signal: SIGKILL
    network_mode: 'host'
    stdin_open: true
    tty: true
    privileged: true
    env_file:
      - ./envs/.env
    volumes:
      - .:/home/node/app
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ~/.docker/config.json:/home/node/.docker/config.json:ro
    ports:
      - 3001:3000
