version: '3'

services:
  app:
    build: .
    command: .docker/start.dev.sh
    stop_signal: SIGKILL
    stdin_open: true
    tty: true
    env_file:
      - ./envs/.env
    volumes:
      - .:/home/node/app
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 3000:3000
    
