name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - run: cat /etc/docker/daemon.json

    - run: cat /etc/group
    
    - name: Build the Docker image
      run: docker build --file Dockerfile --tag my-image-name --build-arg DOCKER_GROUP_ID=127 .
    

    - name: Build the Docker image
      run: docker run -d --name test -v /var/run/docker.sock:/var/run/docker.sock my-image-name

    - name: docker exec
      run: docker exec test docker ps
