name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name
    
    - name: Build the Docker image
      run: docker run -it -v /var/run/docker.sock:/var/run/docker.sock my-image-name docker ps
